#Requires -Version 7.4
<#
.SYNOPSIS
Install the repo git hooks into .git/hooks so the gates are ENFORCED (structural gate G8), not opt-in.

.DESCRIPTION
Writes a POSIX-sh shim for each hook into .git/hooks; git runs hooks via sh (incl. on Windows via the bundled
sh.exe), and the shim execs pwsh against the repo's tools/hooks/<Hook>.ps1 — so the hook logic lives in-repo
(versioned, reviewable) and .git/hooks just points at it.

  pre-push   → tools/hooks/Hook-PrePush.ps1   (runs the pre-push gauntlet · blocks push on failure)
  pre-commit → tools/hooks/Hook-PreCommit.ps1 (L1 parse + anti-attribution + secret/silent-catch checks)

Idempotent (overwrites the shims). Run once per clone. `git push/commit --no-verify` bypass is a BANNED action.
#>
[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
$repo = (Resolve-Path "$PSScriptRoot\..\..").Path
$hooksDir = Join-Path $repo '.git/hooks'
if (-not (Test-Path $hooksDir)) { throw "[Install-GitHooks] .git/hooks not found ($hooksDir) — run inside the repo working tree." }

function Install-XdrHookShim {
    param([Parameter(Mandatory)][string] $HookName, [Parameter(Mandatory)][string] $ScriptName)
    $target = Join-Path $repo "tools/hooks/$ScriptName"
    if (-not (Test-Path $target)) { Write-Host "[Install-GitHooks] SKIP $HookName · $ScriptName not present"; return }
    # POSIX sh shim · resolve the repo root at run time so it works from any worktree. exec pwsh against the in-repo hook.
    $shim = "#!/bin/sh`n# XdrLogRaider $HookName hook - auto-generated by tools/hooks/Install-GitHooks.ps1 - DO NOT EDIT.`nexec pwsh -NoProfile -File `"`$(git rev-parse --show-toplevel)/tools/hooks/$ScriptName`" `"`$@`"`n"
    $path = Join-Path $hooksDir $HookName
    Set-Content -Path $path -Value $shim -NoNewline -Encoding ascii
    if ($IsLinux -or $IsMacOS) { & chmod +x $path }   # *nix needs the exec bit; the Windows sh runner ignores it
    Write-Host "[Install-GitHooks] installed $HookName → tools/hooks/$ScriptName"
}

Install-XdrHookShim -HookName 'pre-push'   -ScriptName 'Hook-PrePush.ps1'
Install-XdrHookShim -HookName 'pre-commit' -ScriptName 'Hook-PreCommit.ps1'
Write-Host "[Install-GitHooks] done · hooks ENFORCED. Bypassing with --no-verify is a BANNED operator action (plan §H)."
