  /Roles/{roleId}/RoleAssignments:
    parameters:
      - $ref: common.yml#/components/parameters/XMsClientRequestId
      - name: roleId
        description: The unique identifier of the role
        in: path
        required: true
        schema:
          $ref: common.yml#/components/schemas/objectId
      - name: scope
        description: The scope of the role assignment
        in: query
        required: true
        schema:
          type: string
          example: '/'
    put:
      summary: Create user role assignment
      description: >-
        Create a role assignment for a user.
      operationId: Role.Assignments.Create
      tags: [Roles]
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: common.yml#/components/schemas/userId
      responses:
        '200':
          description: OK
          headers:
            Cache-Control:
              $ref: common.yml#/components/headers/Cache-Control
            Content-Encoding:
              $ref: common.yml#/components/headers/Content-Encoding
            Vary:
              $ref: common.yml#/components/headers/Vary
            X-Content-Type-Options:
              $ref: common.yml#/components/headers/X-Content-Type-Options
            X-XSS-Protection:
              $ref: common.yml#/components/headers/X-XSS-Protection
            x-ms-version:
              $ref: common.yml#/components/headers/x-ms-version
            Strict-Transport-Security:
              $ref: common.yml#/components/headers/Strict-Transport-Security
            Access-Control-Expose-Headers:
              $ref: common.yml#/components/headers/Access-Control-Expose-Headers
            x-ms-correlation-id:
              $ref: common.yml#/components/headers/x-ms-correlation-id
            x-ms-operation-maturity:
              $ref: common.yml#/components/headers/x-ms-operation-maturity
            x-ms-expected-duration:
              $ref: common.yml#/components/headers/x-ms-expected-duration
            X-UA-Compatible:
              $ref: common.yml#/components/headers/X-UA-Compatible
            Date:
              $ref: common.yml#/components/headers/Date
            Content-Length:
              $ref: common.yml#/components/headers/Content-Length
          content:
            application/json:
              schema:
                type: object
                description: Map of principal ID to assignment ID
        4XX:
          $ref: common.yml#/components/responses/ClientException
    delete:
      summary: Delete user role assignment
      description: >-
        Delete a role assignment for a user.
      operationId: Role.Assignments.Delete
      tags: [Roles]
      responses:
        '204':
          description: No Content
          headers:
            Cache-Control:
              $ref: common.yml#/components/headers/Cache-Control
            Content-Encoding:
              $ref: common.yml#/components/headers/Content-Encoding
            Vary:
              $ref: common.yml#/components/headers/Vary
            X-Content-Type-Options:
              $ref: common.yml#/components/headers/X-Content-Type-Options
            X-XSS-Protection:
              $ref: common.yml#/components/headers/X-XSS-Protection
            x-ms-version:
              $ref: common.yml#/components/headers/x-ms-version
            Strict-Transport-Security:
              $ref: common.yml#/components/headers/Strict-Transport-Security
            Access-Control-Expose-Headers:
              $ref: common.yml#/components/headers/Access-Control-Expose-Headers
            x-ms-correlation-id:
              $ref: common.yml#/components/headers/x-ms-correlation-id
            x-ms-operation-maturity:
              $ref: common.yml#/components/headers/x-ms-operation-maturity
            x-ms-expected-duration:
              $ref: common.yml#/components/headers/x-ms-expected-duration
            X-UA-Compatible:
              $ref: common.yml#/components/headers/X-UA-Compatible
            Date:
              $ref: common.yml#/components/headers/Date
            Content-Length:
              $ref: common.yml#/components/headers/Content-Length
        4XX:
          $ref: common.yml#/components/responses/ClientException
