#Requires -Version 7.4
<#
.SYNOPSIS
LIVE incremental · surgically onboard ONE new Defender category (table + DCR + FA appSetting + per-DCR role +
connector-card sync) to an ALREADY-DEPLOYED XdrLogRaider stack · WITHOUT touching the foundation (Key Vault ·
Function App · Storage).

.DESCRIPTION
This is the live counterpart to dev-tools/Build-MainTemplate.ps1 (which assembles the full marketplace template
for a fresh one-click deploy). Onboard-CategorySurgical adds Category #2..N to an existing RG incrementally:

  1. Build a MINIMAL standalone ARM template from deploy/per-category-schemas/<Portal>-<Category>.json containing
     ONLY the per-category resources — NOTHING from the foundation:
        (a) cross-RG NESTED table deployment  (resourceGroup-only · NO subscriptionId · scope=inner)
        (b) TOP-LEVEL DCR                      (streamDeclarations from the artifact · dependsOn nested simple-name)
     The per-DCR Monitoring Metrics Publisher role (FA SAMI → the new DCR) is ensured POST-DEPLOY via az
     check-then-create (idempotent · an ARM roleAssignment PUT 409s RoleAssignmentExists on re-onboard), next to the appSetting merge.
     The minimal template recomputes the SAME deterministic resource names as mainTemplate (namePrefix/suffix from
     deploymentNameSuffix · workspace coords from workspaceResourceId) so the new DCR/table/role bind to the live stack.
     The FA appSetting XDRLR_DCR_<PORTAL>_<CATEGORY> is NOT in the ARM template — it is MERGED post-deploy via
     `az functionapp config appsettings set` (which merges · ARM PUT on siteConfig.appSettings would REPLACE them all
     and force a Microsoft.Web/sites change · which this tool forbids).

  2. Run `az deployment group what-if` on the minimal template and HARD-ASSERT the change set contains
        0 × Microsoft.KeyVault/*   AND   0 × Microsoft.Web/sites
     (Create/Modify/Delete/Deploy). FAIL CLOSED if it would touch either — the whole point is to never risk the
     KeyVault secrets or bounce/replace the Function App during a category add.

  3. Only with -Apply: `az deployment group create --mode Incremental` (SYNCHRONOUS · no --no-wait), then
     `az functionapp config appsettings set` (merge the XDRLR_DCR_<PORTAL>_<CATEGORY> appSetting) + `az role assignment`
     check-then-create (ensure the FA SAMI's per-DCR Monitoring Metrics Publisher role · idempotent).

Discipline (memory · plan §11.1): NO `--no-wait` on any op · NO bare `--force` · NEVER az group delete. Default is
PLAN-ONLY (what-if + assertion). Applying requires the explicit -Apply switch.

.PARAMETER Portal
e.g. 'Defender'.

.PARAMETER Category
e.g. 'Alerts' · 'Incidents'. Case-sensitive · matches the artifact / manifest Category.

.PARAMETER ResourceGroup
The connector RG of the already-deployed stack (e.g. 'xdrlograider'). If omitted, falls back to env
XDRLR_TARGET_RG then XDRLR_CONNECTOR_RG.

.PARAMETER ParametersFile
ARM parameters file matching the original deploy (default repo parameters.local.json). Supplies location +
deploymentNameSuffix + workspaceResourceId so names align with the live stack.

.PARAMETER Apply
Actually deploy (what-if assertion must pass first). Default OFF = plan-only.

.PARAMETER SchemaArtifactPath
Override the per-category-schema artifact path (default deploy/per-category-schemas/<Portal>-<Category>.json).

.PARAMETER EmitTemplateOnly
Dry-run · assemble + parse-validate the minimal template, write it to a temp file, emit that path to stdout and
STOP — no az CLI, no what-if, no deploy. Used by the GM-2 surgical-output self-test (assert the emitted DCR dataFlow
carries the artifact's transformKql, not a hardcode) and for offline template inspection.

.PARAMETER SkipConnectorCardSync
After a successful -Apply, suppress the post-add Sentinel connector-card sync (Defect-3). By default the onboard
deploys deploy/connector-card-only.json (the SINGLE dataConnectorDefinition · all shipped categories) to the workspace
RG so the Data Connectors gallery card never lags the onboarded categories. The card-only deploy touches NO foundation
resource (no FA zip reset · no roles). Card-sync failure is NON-FATAL (the category data already landed); set this to
skip it entirely (e.g. when syncing the card out-of-band).

.PARAMETER ConnectorCardTemplate
Path to the targeted card-only ARM template (default deploy/connector-card-only.json · regenerated by
dev-tools/Build-MainTemplate.ps1 from the same card content as mainTemplate). Deployed standalone to the workspace RG.

.PARAMETER ConnectorDefinitionName
The Sentinel connector definition name (default 'XdrLogRaiderDefenderXdr') · MUST match the value the foundation
deploy used (mainTemplate variables.connectorDefinitionName) so the card sync UPDATES the same card, not a new one.

.PARAMETER RecreateTableOnSchemaDrift
When the live workspace table's schema DRIFTS from the target artifact (a column whose TYPE changed — e.g. a
string→boolean re-type — or a newly-ADDED column), DROP+RECREATE the table so the deploy creates it FRESH. An
in-place ARM PUT updates LA's query-time schema (getschema shows the new type) but NOT the ingestion path, so new
rows silently DROP the changed/added columns (live-caught 2026-06-17 · Operations typed cols green-but-null). A
fresh table — how cat-1 Exposure got its working typed cols — has a consistent ingest+query schema. DESTRUCTIVE:
drops existing rows in the table (re-poll repopulates · purge-then-reingest re-baseline). Default OFF = FAIL CLOSED
with a clear message when drift is detected (never silently in-place-modify a typed column into a stale schema).

.PARAMETER PurgeNonEmptyOnDrift
OPTIONAL companion to -RecreateTableOnSchemaDrift (NOT required): a drop+recreate of a NON-EMPTY table already applies
the new schema fresh-typed (live-proven 2026-06-20 — a populated 50-col table recreated to the full 65-col target, NO
soft-restore of the schema), so the recreate proceeds with OR without this flag. When SET, it FIRST runs a management-
plane data PURGE (async · polled to completion) so the old rows do not linger as soft-restored pre-deploy clutter —
purely COSMETIC (the windowed verifier already excludes pre-deploy rows + the next poll re-emits fresh-typed). NON-
BLOCKING: an incomplete purge WARNS and proceeds to the drop anyway. DESTRUCTIVE on our own _CL data only (authorized ·
never an RG/unrelated deletion). Default OFF = drop+recreate directly (no purge · the old rows are cosmetic).

.OUTPUTS
Exit 0 · what-if clean (and applied if -Apply) · non-zero · assertion failed / az error / bad inputs.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $Portal,
    [Parameter(Mandatory)] [string] $Category,
    [string] $ResourceGroup,
    [string] $ParametersFile = (Join-Path (Resolve-Path "$PSScriptRoot\..").Path 'parameters.local.json'),
    [string] $SchemaArtifactPath,
    [switch] $Apply,
    [switch] $RecreateTableOnSchemaDrift,
    [switch] $PurgeNonEmptyOnDrift,
    [switch] $EmitTemplateOnly,
    [switch] $SkipConnectorCardSync,
    [string] $ConnectorCardTemplate = (Join-Path (Resolve-Path "$PSScriptRoot\..").Path 'deploy\connector-card-only.json'),
    [string] $ConnectorDefinitionName = 'XdrLogRaiderDefenderXdr',
    [string] $StorageAccount = $env:XDRLR_STORAGE_ACCOUNT   # FA storage acct for the post-recreate checkpoint reset (BoundaryDeduped-after-recreate fix). Omit → Save-XdrCheckpointReset self-resolves from .env.local XDRLR_STORAGE_ACCOUNT.
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# Blocker-fix · canonical category tokenizer (single source w/ catalogue/manifest/schema/Build-MainTemplate) so a spaced/
# '&' category yields ARM-safe resource names that BIND to the live stack (raw $Category kept the space -> name mismatch).
Import-Module (Join-Path $PSScriptRoot '..\src\Modules\Xdr.Common.Parser\Xdr.Common.Parser.psd1') -Force -DisableNameChecking -ErrorAction Stop
$repoRoot = (Resolve-Path "$PSScriptRoot\..").Path
$JsonDepth = 60

# ─── Pure what-if safety predicate (extracted · unit-tested via the dot-source seam below) ─────────
function Test-XdrChangeTouchesFoundation {
    <#
      Returns $true iff a single `az deployment group what-if` change entry would MUTATE a FOUNDATION resource
      (Microsoft.KeyVault/* or Microsoft.Web/sites) — the surgical add must NEVER do this (fail closed).
      · NoChange / Ignore        -> $false (no mutation).
      · Create / Modify / Delete -> $true iff the TARGET resourceId's /providers/<type> segment is forbidden.
      · Unsupported              -> what-if could not evaluate the change. This arises ONLY for a resource whose
        identity depends on a runtime reference() (here exclusively the per-DCR role · guid seeded by
        reference(FA).principalId). A KV/Web mutation has a STATIC identity and is always evaluable, never Unsupported.
        The role's raw resourceId expression INCIDENTALLY contains the FA id inside reference() (a READ of principalId,
        NOT a change) so a naive substring scan false-trips. Allow ONLY the per-DCR roleAssignment; fail closed on any
        OTHER opaque change.
    #>
    [OutputType([bool])]
    param([string] $ChangeType, [string] $ResId)
    if ($ChangeType -in @('NoChange', 'Ignore')) { return $false }
    if ($ChangeType -eq 'Unsupported') {
        if ($ResId -match 'Microsoft\.Authorization/roleAssignments' -and $ResId -match 'dataCollectionRules') { return $false }
        return $true   # unknown opaque change · fail closed
    }
    return ($ResId -match [regex]::Escape('/providers/Microsoft.KeyVault/') -or $ResId -match [regex]::Escape('/providers/Microsoft.Web/sites'))
}

# ─── Pure table-schema-drift predicate (extracted · unit-tested via the dot-source seam below) ─────
function Test-XdrTableColumnDrift {
    <#
      Returns the list of TARGET columns whose (name→type) is MISSING-from or MISTYPED-vs the LIVE table schema.
      A non-empty result means an in-place ARM PUT would NOT reliably apply the schema: LA cannot change an existing
      column's type (string→boolean is rejected outright · the table keeps string while the DCR stream becomes
      boolean → a mismatch the ingestion path silently DROPS) and an in-place column ADD leaves the ingestion schema
      stale (new rows drop the added col) — both live-caught 2026-06-17 (Operations typed cols green-but-null). The
      ONLY reliable fix is DROP+RECREATE (fresh ingest+query schema · how cat-1 Exposure got its working typed cols).
      Name compared case-insensitively (hashtable default); type normalized lower-invariant (LA 'dateTime' ==
      artifact 'datetime'). Extra LIVE columns (LA-managed TimeGenerated/TenantId/Type/_ResourceId) are IGNORED —
      only the TARGET columns must land, so drift is one-directional (target ⊄ live).
    #>
    [OutputType([string[]])]
    param([object[]] $TargetCols, [object[]] $LiveCols)
    $liveMap = @{}
    foreach ($lc in @($LiveCols)) { if ($lc -and $lc.name) { $liveMap[[string]$lc.name] = (Get-XdrCanonicalColType ([string]$lc.type)) } }
    $drift = [System.Collections.Generic.List[string]]::new()
    foreach ($tc in @($TargetCols)) {
        if (-not $tc -or -not $tc.name) { continue }
        $tn = [string]$tc.name
        $tt = Get-XdrCanonicalColType ([string]$tc.type)
        if (-not $liveMap.ContainsKey($tn)) { $drift.Add("ADD $tn ($tt)"); continue }
        if ($liveMap[$tn] -ne $tt) { $drift.Add("RETYPE $tn ($($liveMap[$tn])->$tt)") }
    }
    return $drift.ToArray()
}

# Canonical column-type normalizer · ARM/artifact names (boolean,dateTime,int) vs KQL getschema names (bool,datetime,long).
# Map both to a canonical form so 'boolean'=='bool' and 'dateTime'=='datetime' are NOT read as false drift; int folds
# into long (LA stores int32 as long effectively · harmless widening). Used by Test-XdrTableColumnDrift to compare the
# artifact's target types against the table's EFFECTIVE (getschema) types.
function Get-XdrCanonicalColType {
    [OutputType([string])]
    param([string] $Type)
    switch (([string]$Type).Trim().ToLowerInvariant()) {
        'boolean' { 'bool' }
        'int'     { 'long' }
        'int32'   { 'long' }
        'int64'   { 'long' }
        'date'    { 'datetime' }
        default   { ([string]$Type).Trim().ToLowerInvariant() }
    }
}

# Dot-source seam (unit test): define functions, then STOP before any input resolution / az / deploy work.
if ($env:XDRLR_ONBOARD_DOTSOURCE_ONLY -eq '1') { return }

# ─── Resolve inputs ──────────────────────────────────────────────────────────────────────────────
if (-not $ResourceGroup) { $ResourceGroup = $env:XDRLR_TARGET_RG }
if (-not $ResourceGroup) { $ResourceGroup = $env:XDRLR_CONNECTOR_RG }
if (-not $ResourceGroup) { throw "[Onboard-CategorySurgical] -ResourceGroup not supplied and neither XDRLR_TARGET_RG nor XDRLR_CONNECTOR_RG is set" }

if (-not $SchemaArtifactPath) {
    $SchemaArtifactPath = Join-Path $repoRoot "deploy/per-category-schemas/$Portal-$Category.json"
}
if (-not (Test-Path $SchemaArtifactPath)) {
    throw "[Onboard-CategorySurgical] schema artifact not found: $SchemaArtifactPath · run dev-tools/Build-PerCategorySchema.ps1 -Portal $Portal -Category $Category first"
}
if (-not (Test-Path $ParametersFile)) {
    throw "[Onboard-CategorySurgical] parameters file not found: $ParametersFile (need location + deploymentNameSuffix + workspaceResourceId to align names with the live stack)"
}
if (-not $EmitTemplateOnly -and -not (Get-Command az -ErrorAction SilentlyContinue)) {
    throw "[Onboard-CategorySurgical] az CLI not found · required for what-if/deploy"
}

$catToken = Get-XdrCategoryToken -Category $Category   # canonical token · single source · spaced/'&' names -> ARM-safe
$catLower = $catToken.ToLowerInvariant()
$artifact = Get-Content $SchemaArtifactPath -Raw | ConvertFrom-Json -Depth $JsonDepth

$tableName = $artifact.TableResource.properties.schema.name
if (-not $tableName) { $tableName = "${Portal}_${Category}_CL" }
$tableCols = @($artifact.TableResource.properties.schema.columns)
$streamProp = @($artifact.DcrResource.properties.streamDeclarations.PSObject.Properties)[0]
if (-not $streamProp) { throw "[Onboard-CategorySurgical] artifact DcrResource has no streamDeclarations" }
$streamName = $streamProp.Name
$dcrCols    = @($streamProp.Value.columns)
if ($tableCols.Count -eq 0 -or $dcrCols.Count -eq 0) { throw "[Onboard-CategorySurgical] artifact table/DCR columns empty" }
# GM-2 (2026-06-16) · carry the artifact's DCR dataFlow transformKql VERBATIM (NEVER hardcode 'source' at the dataFlow
# below). ONE shared single-source helper with Build-MainTemplate's Get-StreamInfo (Parser.Get-XdrArtifactTransformKql)
# so the surgical onboard and the marketplace writer can never drift. Under approach B every category is the identity
# 'source'; this preserves any future non-identity transform an artifact might carry through the surgical path too.
$transformKql = Get-XdrArtifactTransformKql -DcrResource $artifact.DcrResource

$appSettingName = "XDRLR_DCR_$($Portal.ToUpper())_$($catToken.ToUpper())"
$nestedNameExpr = "[concat(variables('namePrefix'), '-table-$catLower-', variables('suffix'))]"
$dcrNameExpr    = "[concat(variables('namePrefix'), '-dcr-$catLower-', variables('suffix'))]"
$dcrNameInner   = "concat(variables('namePrefix'), '-dcr-$catLower-', variables('suffix'))"

Write-Host "================================================================"
Write-Host "Onboard-CategorySurgical · $Portal/$Category"
Write-Host "  RG          : $ResourceGroup"
Write-Host "  artifact    : $SchemaArtifactPath"
Write-Host "  table       : $tableName ($($tableCols.Count) cols)"
Write-Host "  DCR stream  : $streamName ($($dcrCols.Count) cols)"
Write-Host "  appSetting  : $appSettingName (merged post-deploy · NOT in ARM)"
Write-Host "  mode        : $(if ($Apply) { 'APPLY (what-if gate first)' } else { 'PLAN-ONLY (what-if + assert)' })"
Write-Host "================================================================"

# ─── Build the MINIMAL per-category ARM template (foundation-free) ────────────────────────────────
# Variables recompute the SAME deterministic names as mainTemplate so the new resources bind to the live stack.
$minimal = [ordered]@{
    '$schema'      = 'https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#'
    contentVersion = '1.0.0.0'
    metadata       = [ordered]@{
        _generator = [ordered]@{ name = 'XdrLogRaider'; version = '0.1.0'; tool = 'Onboard-CategorySurgical' }
        description = "Surgical per-category add for $Portal/$Category · table + DCR ONLY · NO foundation (KeyVault/FunctionApp/Storage untouched). The FA appSetting $appSettingName AND the per-DCR Monitoring Metrics Publisher role are ensured POST-DEPLOY via az (idempotent · an ARM role PUT 409s on re-onboard)."
    }
    parameters     = [ordered]@{
        location             = [ordered]@{ type = 'string'; defaultValue = '[resourceGroup().location]' }
        deploymentNameSuffix = [ordered]@{ type = 'string'; defaultValue = '[take(uniqueString(resourceGroup().id), 6)]' }
        workspaceResourceId  = [ordered]@{ type = 'string' }
    }
    variables      = [ordered]@{
        namePrefix                       = 'xdrlr'
        suffix                           = "[parameters('deploymentNameSuffix')]"
        functionAppName                  = "[concat(variables('namePrefix'), '-fa-', variables('suffix'))]"
        dceName                          = "[concat(variables('namePrefix'), '-dce-', variables('suffix'))]"
        workspaceResourceGroup           = "[split(parameters('workspaceResourceId'), '/')[4]]"
        workspaceName                    = "[last(split(parameters('workspaceResourceId'), '/'))]"
        monitoringMetricsPublisherRoleId = "[subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '3913510d-42f4-4e42-8a64-420c390055eb')]"
        tags                             = [ordered]@{
            connector = 'XdrLogRaider'; connectorVersion = '0.1.0'; env = 'production'; managedBy = 'ARM'
        }
    }
    resources      = @(
        # (a) cross-RG nested table deployment · resourceGroup-only · scope=inner.
        [ordered]@{
            comments      = "Surgical add · per-category '$Portal/$Category' workspace table. Cross-RG nested (resourceGroup-only · NO subscriptionId). Table MUST exist before the DCR streamDeclarations bind (DCR dependsOn this nested · simple-name form)."
            type          = 'Microsoft.Resources/deployments'
            apiVersion    = '2022-09-01'
            name          = $nestedNameExpr
            resourceGroup = "[variables('workspaceResourceGroup')]"
            properties    = [ordered]@{
                mode = 'Incremental'
                expressionEvaluationOptions = [ordered]@{ scope = 'inner' }
                parameters = [ordered]@{
                    workspaceName = [ordered]@{ value = "[variables('workspaceName')]" }
                    tableName     = [ordered]@{ value = $tableName }
                }
                template = [ordered]@{
                    '$schema'      = 'https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#'
                    contentVersion = '1.0.0.0'
                    parameters = [ordered]@{
                        workspaceName = [ordered]@{ type = 'string' }
                        tableName     = [ordered]@{ type = 'string' }
                    }
                    resources = @(
                        [ordered]@{
                            comments   = "Custom workspace table · $tableName · Analytics plan"
                            type       = 'Microsoft.OperationalInsights/workspaces/tables'
                            apiVersion = '2023-09-01'
                            name       = "[concat(parameters('workspaceName'), '/', parameters('tableName'))]"
                            properties = [ordered]@{
                                plan   = 'Analytics'
                                schema = [ordered]@{ name = "[parameters('tableName')]"; columns = $tableCols }
                            }
                        }
                    )
                    outputs = [ordered]@{}
                }
            }
        }
        # (b) top-level DCR · dependsOn the IN-TEMPLATE nested table ONLY (the DCE is EXTERNAL · bound via the
        # dataCollectionEndpointId property, NOT dependsOn · see the dependsOn note below).
        [ordered]@{
            comments   = "Surgical add · per-category '$Portal/$Category' DCR. dependsOn the nested table deployment via SIMPLE-NAME string form (NOT resourceId() · ARM rejects resourceId() for cross-RG nested · iter#5 ordering fix). Columns set-equal to the table by construction. The DCE is EXTERNAL (foundation) so it is bound via the dataCollectionEndpointId property only · NOT a dependsOn target (ARM InvalidTemplate · live-validate 2026-06-16)."
            type       = 'Microsoft.Insights/dataCollectionRules'
            apiVersion = '2023-03-11'
            name       = $dcrNameExpr
            location   = "[parameters('location')]"
            tags       = "[variables('tags')]"
            dependsOn  = @(
                # NOT the DCE here: it is an EXTERNAL foundation resource (NOT defined in this surgical template).
                # ARM dependsOn accepts ONLY in-template targets, so depending on the external DCE -> InvalidTemplate at
                # deploy ("The resource 'Microsoft.Insights/dataCollectionEndpoints/...' is not defined in the template").
                # what-if was lenient and passed; the real az deployment-validate caught it (live re-prove · 2026-06-16).
                # The DCE is still bound via the dataCollectionEndpointId property below (a resourceId() string is valid
                # for an external resource) and already exists from the foundation deploy, so no ordering dep is needed.
                $nestedNameExpr
            )
            properties = [ordered]@{
                dataCollectionEndpointId = "[resourceId('Microsoft.Insights/dataCollectionEndpoints', variables('dceName'))]"
                streamDeclarations = [ordered]@{ $streamName = [ordered]@{ columns = $dcrCols } }
                destinations = [ordered]@{
                    logAnalytics = @( [ordered]@{ workspaceResourceId = "[parameters('workspaceResourceId')]"; name = 'xdrlrWorkspace' } )
                }
                dataFlows = @(
                    [ordered]@{ streams = @($streamName); destinations = @('xdrlrWorkspace'); transformKql = $transformKql; outputStream = $streamName }
                )
            }
        }
        # (d) per-DCR Monitoring Metrics Publisher role (FA SAMI → this DCR) is ensured POST-DEPLOY via az, NOT in this
        # ARM template. An ARM roleAssignment PUT returns RoleAssignmentExists (409) whenever the (FA-SAMI, role, DCR)
        # TUPLE already has an assignment under ANY name — which is true for every already-onboarded category (the
        # foundation deploy named it with a guid the surgical template cannot reproduce · a deterministic guid only
        # collides by luck · cat-1 matched, Operations did not · live-caught 2026-06-16). az role assignment create is
        # idempotent at the tuple level (we check-then-create), so it works for BOTH a fresh category and a re-onboard
        # regardless of the existing assignment's name. See the post-deploy "ensure per-DCR role" step below.
        # (Build-MainTemplate still grants it in ARM for the one-shot FRESH deploy, where no prior assignment exists.)
    )
    outputs        = [ordered]@{
        dcrName        = [ordered]@{ type = 'string'; value = $dcrNameExpr }
        dcrImmutableId = [ordered]@{ type = 'string'; value = "[reference(resourceId('Microsoft.Insights/dataCollectionRules', $dcrNameInner), '2023-03-11').immutableId]" }
        tableName      = [ordered]@{ type = 'string'; value = $tableName }
        appSettingName = [ordered]@{ type = 'string'; value = $appSettingName }
    }
}

$tmpTemplate = Join-Path ([IO.Path]::GetTempPath()) ("xdrlr-surgical-$Portal-$Category-" + [Guid]::NewGuid().ToString('N') + '.json')
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllText($tmpTemplate, ($minimal | ConvertTo-Json -Depth $JsonDepth), $utf8NoBom)

# Parse-validate the minimal template before sending to Azure.
try { $null = Get-Content $tmpTemplate -Raw | ConvertFrom-Json -Depth $JsonDepth }
catch { Remove-Item $tmpTemplate -Force -ErrorAction SilentlyContinue; throw "[Onboard-CategorySurgical] minimal template does not parse: $($_.Exception.Message)" }
Write-Host "[Onboard-CategorySurgical] minimal template → $tmpTemplate"

if ($EmitTemplateOnly) {
    # GM-2 dry-run / self-test hook · STOP before any az call (no params read, no what-if, no deploy). Emit the
    # assembled template path to stdout (Output stream · the LAST/only object) so the surgical-output gauntlet can
    # assert the DCR dataFlow carries the artifact transformKql with ZERO Azure dependency. Caller deletes the temp.
    Write-Output $tmpTemplate
    return
}

$epoch = [int][double]::Parse((Get-Date -UFormat %s))
$deploymentName = "xdrlr-surgical-$catLower-$epoch"

# The minimal template declares ONLY location/deploymentNameSuffix/workspaceResourceId. The original
# parameters.local.json carries the FULL foundation parameter set (servicePassword/totpSecret/…) which ARM
# rejects as 'parameters supplied but not defined in the template'. Extract ONLY the 3 we need and pass them
# inline. These three reproduce the SAME deterministic resource names as the original mainTemplate deploy so
# the new table/DCR/role bind to the live stack.
$paramsObj = Get-Content $ParametersFile -Raw | ConvertFrom-Json -Depth 30
function Get-ParamValue {
    param([string] $Name)
    $p = $paramsObj.parameters.PSObject.Properties[$Name]
    if ($p -and $p.Value.PSObject.Properties['value']) { return [string]$p.Value.value }
    return $null
}
$pWorkspaceResId = Get-ParamValue 'workspaceResourceId'
$pSuffix         = Get-ParamValue 'deploymentNameSuffix'
$pLocation       = Get-ParamValue 'location'
if (-not $pWorkspaceResId) { throw "[Onboard-CategorySurgical] parameters file '$ParametersFile' has no workspaceResourceId · cannot align names with the live stack" }
$inlineParams = @("workspaceResourceId=$pWorkspaceResId")
if ($pSuffix)   { $inlineParams += "deploymentNameSuffix=$pSuffix" }   # MUST match original deploy or names diverge
if ($pLocation) { $inlineParams += "location=$pLocation" }
Write-Host "[Onboard-CategorySurgical] inline params: $((@($inlineParams | ForEach-Object { ($_ -split '=',2)[0] })) -join ', ')"
if (-not $pSuffix) {
    Write-Warning "[Onboard-CategorySurgical] deploymentNameSuffix NOT in parameters file · the minimal template will auto-derive take(uniqueString(rg.id),6) · this matches the original ONLY if the original also defaulted it. If the live stack used an explicit suffix, set it in the parameters file or names will not match."
}

try {
    # Tracks whether the schema-drift path DROPPED the live table this run. Initialized $false BEFORE the drift block
    # (Set-StrictMode -Version Latest · must exist before any read). When $true, the -Apply tail AUTO-resets the FA
    # exactly-once checkpoint so the runtime re-emits from a clean baseline into the now-empty recreated table — without
    # it the next poll sees the rows as already-sent → Entry.Poll.BoundaryDeduped → 0 rows land (BoundaryDeduped-after-
    # recreate · live-caught 2026-06-25: GetTvmRiskScore/List SUCCEEDED but BoundaryDeduped into the empty table).
    $didRecreateTable = $false
    # NEW columns this recreate ADDS (names only · parsed from the SAME $drift "ADD <name> (<type>)" entries the diff below
    # logs — never recomputed differently). Pre-existing cols + id are unaffected by the recreate; only these NEW cols are
    # subject to the ~10-15 min Azure DCR schema-propagation lag, so the FIRST re-emit after the checkpoint reset can land
    # THEM empty (PROPAGATION-PENDING · live-caught this session). Initialized [] BEFORE the drift block (Set-StrictMode).
    $addedColumns = @()
    # ─── Recreate-on-schema-drift guard (BEFORE what-if · in-place LA table modify silently corrupts ingestion) ──
    # The table is deployed as a Microsoft.OperationalInsights/workspaces/tables ARM resource. On an EXISTING table an
    # ARM PUT does an IN-PLACE modify: LA updates the query-time schema (getschema reflects it) but the INGESTION-time
    # schema goes stale, so new rows silently DROP any column whose type changed (string→boolean is rejected outright)
    # or that was newly added (live-caught 2026-06-17 · Operations GetTenantContext typed cols green-but-null). A FRESH
    # table has a consistent ingest+query schema. Detect drift; DROP+RECREATE with -RecreateTableOnSchemaDrift, else
    # FAIL CLOSED (never silently in-place-modify into a stale schema). Table delete is cross-RG (the workspace RG).
    $wsParts = @($pWorkspaceResId -split '/')
    $wsRG    = $wsParts[4]
    $wsName  = $wsParts[-1]
    # EFFECTIVE schema via KQL getschema (NOT `table show` · the DECLARED schema DIVERGES from the effective/ingestion
    # schema after a failed in-place type change — `table show` optimistically reports the target type the ARM PUT
    # requested while getschema reports the actual stored type that governs ingestion · IsSuspended declared=boolean /
    # effective=string live-caught 2026-06-17). Resolve the workspace customerId for the LA query API.
    $wsCustomerId = az monitor log-analytics workspace show --ids $pWorkspaceResId --query customerId -o tsv 2>$null
    $liveCols = @(); $tableExists = $false
    if ($wsCustomerId) {
        $schemaRaw = az monitor log-analytics query --workspace $wsCustomerId --analytics-query "$tableName | getschema | project ColumnName, ColumnType" -o json 2>$null
        if ($LASTEXITCODE -eq 0 -and $schemaRaw) {
            $rows = @($schemaRaw | ConvertFrom-Json -Depth 30)
            if ($rows.Count -gt 0) { $tableExists = $true; $liveCols = @($rows | ForEach-Object { [pscustomobject]@{ name = $_.ColumnName; type = $_.ColumnType } }) }
        }
    } else {
        Write-Warning "[Onboard-CategorySurgical] could not resolve workspace customerId from '$pWorkspaceResId' · skipping the effective-schema drift check (an in-place type-change would silently fail · verify typed cols populate post-deploy)."
    }
    if ($tableExists) {
        $drift = @(Test-XdrTableColumnDrift -TargetCols $tableCols -LiveCols $liveCols)
        if ($drift.Count -gt 0) {
            Write-Host ""
            Write-Host "[Onboard-CategorySurgical] TABLE SCHEMA DRIFT · live '$tableName' differs from target in $($drift.Count) col(s):" -ForegroundColor Yellow
            $drift | Select-Object -First 60 | ForEach-Object { Write-Host "   ~ $_" -ForegroundColor Yellow }
            # Capture the NEW-column names from the SAME $drift list (entries shaped "ADD <name> (<type>)" · Test-XdrTableColumnDrift
            # line ~169) — these are exactly the cols subject to the DCR schema-propagation lag if we recreate. RETYPE entries are
            # EXCLUDED (those cols pre-exist, so they are not propagation-pending). No recompute — parsed from the diff just logged.
            $addedColumns = @($drift | Where-Object { $_ -like 'ADD *' } | ForEach-Object { ($_ -replace '^ADD\s+([^\s(]+).*$', '$1') })
            if (-not $RecreateTableOnSchemaDrift) {
                throw "[Onboard-CategorySurgical] FAIL CLOSED · live table '$tableName' schema drifts from target · an in-place ARM PUT does NOT reliably apply column type-changes/additions (LA updates the query-time schema but NOT the ingestion path → new rows silently drop the changed cols · live-caught 2026-06-17). Re-run with -RecreateTableOnSchemaDrift to DROP+RECREATE the table fresh (DESTRUCTIVE · drops existing rows in '$tableName' · re-poll repopulates · the proven cat-1 Exposure path)."
            }
            if (-not $Apply) {
                Write-Host "[Onboard-CategorySurgical] PLAN-ONLY · -RecreateTableOnSchemaDrift set · WOULD drop+recreate '$tableName' on -Apply (no mutation in plan mode)." -ForegroundColor Yellow
            } else {
                # DROP+recreate of a same-name table APPLIES THE NEW SCHEMA — live-proven 2026-06-20: a populated 50-col
                # Defender_SecureScore_CL was dropped with NO prior purge and the ARM recreate landed the full 65-col target
                # schema (NOT a 50-col soft-restore). The earlier "soft-restore blocks the retype" guard CONFLATED the REAL
                # in-place-ARM-PUT green-but-null (ADD-cols-WITHOUT-drop · still true · that is WHY we DROP rather than PUT)
                # with a drop+recreate "soft-restore" that does NOT happen on our _CL tables. So a NON-EMPTY table needs NO
                # purge to recreate fresh-typed. The old rows MAY linger as soft-restored DATA, but that is COSMETIC — the
                # windowed verifier (DeployedSinceUtc) excludes pre-deploy rows and the next poll re-emits fresh-typed.
                # -PurgeNonEmptyOnDrift OPTIONALLY clears them first (a cleaner table) but is NOT required and NEVER blocks.
                $cntRaw = az monitor log-analytics query --workspace $wsCustomerId --analytics-query "$tableName | count" -o json 2>$null
                $rowCnt = if ($LASTEXITCODE -eq 0 -and $cntRaw) { [int](@($cntRaw | ConvertFrom-Json)[0].Count) } else { -1 }
                if ($rowCnt -gt 0 -and -not $PurgeNonEmptyOnDrift) {
                    Write-Host "[Onboard-CategorySurgical] '$tableName' has $rowCnt row(s) + drifts · drop+recreate APPLIES the new schema (proven · no soft-restore of the schema) · the old rows are cosmetic (windowed-out + re-polled fresh) · pass -PurgeNonEmptyOnDrift to clear them first. Proceeding to drop+recreate." -ForegroundColor Yellow
                } elseif ($rowCnt -gt 0) {
                    # OPTIONAL cosmetic pre-clean (NOT required for the schema · the recreate is fresh-typed regardless): empty
                    # the table via a management-plane data PURGE using native Invoke-RestMethod (az.cmd mangles a JSON
                    # --filters arg · the SAME no-mangling fix as Force-XdrFullCycle), polled to completion before the drop so
                    # the old rows do not linger. Authorized destructive op on our own _CL data. NEVER a blocker — if the purge
                    # does not complete in budget we WARN and proceed to the drop anyway (the new schema applies regardless).
                    Write-Host "[Onboard-CategorySurgical] '$tableName' has $rowCnt row(s) · -PurgeNonEmptyOnDrift -> OPTIONAL pre-clean data PURGE (all rows) before the drop ..." -ForegroundColor Yellow
                    $mgmtTok = az account get-access-token --resource https://management.azure.com/ --query accessToken -o tsv 2>$null
                    if (-not $mgmtTok) { throw "[Onboard-CategorySurgical] could not acquire a management-plane token for the purge" }
                    $purgeUri = "https://management.azure.com$pWorkspaceResId/purge?api-version=2020-08-01"
                    $purgeBody = @{ table = $tableName; filters = @(@{ column = 'TimeGenerated'; operator = '>'; value = '2020-01-01T00:00:00Z' }) } | ConvertTo-Json -Depth 6
                    # Capture the purge OPERATION handle (x-ms-status-location header and/or body.operationId). The LA purge
                    # is async; its RELIABLE completion signal is the operation STATUS (status=completed), NOT the row-count
                    # KQL — the count LAGS the actual deletion (live-caught 2026-06-19: count stayed flat at 53,630 for the
                    # whole 20-min budget while the purge was in flight). Poll the operation; keep the count only as a fallback
                    # when no operation handle is returned.
                    $respHdrs = $null; $purgeResp = $null
                    try { $purgeResp = Invoke-RestMethod -Method Post -Uri $purgeUri -Headers @{ Authorization = "Bearer $mgmtTok" } -ContentType 'application/json' -Body $purgeBody -ResponseHeadersVariable respHdrs -TimeoutSec 60 -ErrorAction Stop }
                    catch { throw "[Onboard-CategorySurgical] PURGE submit failed for '$tableName': $($_.Exception.Message)" }
                    $statusUrl = ''
                    if ($respHdrs -and $respHdrs['x-ms-status-location']) { $statusUrl = [string]@($respHdrs['x-ms-status-location'])[0] }
                    if (-not $statusUrl -and $purgeResp -and $purgeResp.PSObject.Properties.Name -contains 'operationId' -and $purgeResp.operationId) {
                        $statusUrl = "https://management.azure.com$pWorkspaceResId/operations/$($purgeResp.operationId)?api-version=2020-08-01"
                    }
                    # The x-ms-status-location header pins api-version=2017-01-01-preview, which Azure no longer registers for
                    # workspaces/operations (live-caught 2026-06-19: GET 404s NoRegisteredProviderFound -> empty status). Normalize
                    # to the supported api-version we POST the purge with, regardless of which source set the URL.
                    if ($statusUrl) { $statusUrl = $statusUrl -replace 'api-version=[^&]+', 'api-version=2020-08-01' }
                    $purged = $false
                    foreach ($pi in 1..120) {   # ~60 min budget @ 30s · the LA purge is async (large tables take longer than 20 min)
                        Start-Sleep -Seconds 30
                        # Re-acquire the management token each poll — over a long (up to 60-min) purge the INITIAL token
                        # EXPIRES (~60-90 min lifetime); an expired token makes the status GET 401 -> empty status -> never
                        # 'completed' (live-caught 2026-06-19: polls 97-120 showed empty status as the token aged out). az
                        # returns a cached still-valid token cheaply, so refreshing every poll is harmless.
                        $mgmtTok = az account get-access-token --resource https://management.azure.com/ --query accessToken -o tsv 2>$null
                        if ($statusUrl) {
                            $st = ''
                            try { $st = [string](Invoke-RestMethod -Method Get -Uri $statusUrl -Headers @{ Authorization = "Bearer $mgmtTok" } -TimeoutSec 60 -ErrorAction Stop).status } catch { $st = '' }
                            Write-Host "[Onboard-CategorySurgical]   purge poll $pi · '$tableName' purge-operation status=$st"
                            if ($st -eq 'completed') { $purged = $true; break }
                        } else {
                            $cRaw = az monitor log-analytics query --workspace $wsCustomerId --analytics-query "$tableName | count" -o json 2>$null
                            $c = if ($LASTEXITCODE -eq 0 -and $cRaw) { [int](@($cRaw | ConvertFrom-Json)[0].Count) } else { -1 }
                            Write-Host "[Onboard-CategorySurgical]   purge poll $pi · '$tableName' count=$c (no operation handle · count-fallback)"
                            if ($c -eq 0) { $purged = $true; break }
                        }
                    }
                    if (-not $purged) { Write-Host "[Onboard-CategorySurgical] '$tableName' OPTIONAL pre-clean purge did not complete in budget (async · still in flight) · PROCEEDING to drop+recreate anyway — the new schema applies regardless and the old rows are windowed-out (cosmetic)." -ForegroundColor Yellow }
                    else { Write-Host "[Onboard-CategorySurgical] '$tableName' purged to 0 · proceeding to drop+recreate fresh-typed." -ForegroundColor Green }
                }
                Write-Host "[Onboard-CategorySurgical] DROPPING '$tableName' so the ARM deploy recreates it FRESH-typed (the new schema applies regardless of prior rows · proven 2026-06-20) ..." -ForegroundColor Yellow
                az monitor log-analytics workspace table delete --resource-group $wsRG --workspace-name $wsName --name $tableName --yes --output none
                if ($LASTEXITCODE -ne 0) { throw "[Onboard-CategorySurgical] table delete FAILED (az exit $LASTEXITCODE) · NOT proceeding" }
                $didRecreateTable = $true   # → the -Apply tail must reset the FA checkpoint so the runtime re-emits into the empty table (BoundaryDeduped-after-recreate fix)
                Write-Host "[Onboard-CategorySurgical] dropped '$tableName' · the ARM deploy recreates it fresh-typed." -ForegroundColor Green
            }
        } else {
            Write-Host "[Onboard-CategorySurgical] live table '$tableName' schema matches target ($($tableCols.Count) target cols) · no recreate needed."
        }
    } else {
        Write-Host "[Onboard-CategorySurgical] table '$tableName' not present yet · ARM will create it fresh."
    }

    # ─── what-if + HARD ASSERT (fail closed on any KeyVault / Web/sites change) ───────────────────
    Write-Host ""
    Write-Host "[Onboard-CategorySurgical] az deployment group what-if (RG=$ResourceGroup) ..."
    $whatIfJson = az deployment group what-if `
        --resource-group $ResourceGroup `
        --template-file $tmpTemplate `
        --parameters $inlineParams `
        --name $deploymentName `
        --no-pretty-print `
        --output json 2>&1 | Out-String
    $whatIfRc = $LASTEXITCODE
    if ($whatIfRc -ne 0) {
        Write-Host $whatIfJson
        throw "[Onboard-CategorySurgical] what-if FAILED (az exit $whatIfRc) · NOT applying"
    }

    $changes = $null
    try { $changes = ($whatIfJson | ConvertFrom-Json -Depth 60).changes }
    catch { Write-Warning "[Onboard-CategorySurgical] what-if JSON parse failed: $($_.Exception.Message)" }
    if ($null -eq $changes) {
        throw "[Onboard-CategorySurgical] could not parse what-if 'changes' array · refusing to apply (fail closed). Raw: $($whatIfJson.Substring(0,[Math]::Min(500,$whatIfJson.Length)))"
    }

    # Fail closed on any change that would MUTATE a foundation KeyVault/Web-sites resource (predicate is unit-tested).
    $offending = @()
    foreach ($c in $changes) {
        $changeType = [string]$c.changeType
        $resId = ''
        if ($c.PSObject.Properties['resourceId'] -and $c.resourceId) { $resId = [string]$c.resourceId }
        elseif ($c.PSObject.Properties['after'] -and $c.after -and $c.after.PSObject.Properties['id']) { $resId = [string]$c.after.id }
        elseif ($c.PSObject.Properties['before'] -and $c.before -and $c.before.PSObject.Properties['id']) { $resId = [string]$c.before.id }
        if (Test-XdrChangeTouchesFoundation -ChangeType $changeType -ResId $resId) { $offending += "[$changeType] $resId" }
    }

    Write-Host ""
    Write-Host "[Onboard-CategorySurgical] what-if change summary:"
    foreach ($c in $changes) {
        $rid = if ($c.PSObject.Properties['resourceId']) { $c.resourceId } else { '<id-in-after/before>' }
        Write-Host ("   {0,-8} {1}" -f ([string]$c.changeType), $rid)
    }

    if ($offending.Count -gt 0) {
        Write-Host ""
        Write-Host "[Onboard-CategorySurgical] HARD-ASSERT FAILED · what-if would touch FOUNDATION resources (forbidden):" -ForegroundColor Red
        $offending | ForEach-Object { Write-Host "   ! $_" -ForegroundColor Red }
        throw "[Onboard-CategorySurgical] FAIL CLOSED · surgical add must NOT change any Microsoft.KeyVault/* or Microsoft.Web/sites resource · refusing to apply"
    }
    Write-Host "[Onboard-CategorySurgical] HARD-ASSERT PASS · 0 Microsoft.KeyVault/* and 0 Microsoft.Web/sites changes in the change set."

    if (-not $Apply) {
        Write-Host ""
        Write-Host "[Onboard-CategorySurgical] PLAN-ONLY · what-if clean · re-run with -Apply to deploy."
        exit 0
    }

    # ─── Apply · synchronous incremental create (NO --no-wait) ────────────────────────────────────
    Write-Host ""
    Write-Host "[Onboard-CategorySurgical] az deployment group create --mode Incremental (synchronous) ..."
    az deployment group create `
        --resource-group $ResourceGroup `
        --template-file $tmpTemplate `
        --parameters $inlineParams `
        --name $deploymentName `
        --mode Incremental `
        --output none
    if ($LASTEXITCODE -ne 0) { throw "[Onboard-CategorySurgical] deployment create FAILED (az exit $LASTEXITCODE)" }

    # Read the DCR immutableId from deployment outputs → set the appSetting (MERGE · not replace).
    $immId = az deployment group show --resource-group $ResourceGroup --name $deploymentName --query 'properties.outputs.dcrImmutableId.value' -o tsv 2>$null
    if (-not $immId) { throw "[Onboard-CategorySurgical] could not read dcrImmutableId from deployment outputs · NOT setting appSetting" }

    $faName = az resource list --resource-group $ResourceGroup --resource-type 'Microsoft.Web/sites' --query '[0].name' -o tsv 2>$null
    if (-not $faName) { throw "[Onboard-CategorySurgical] no Function App in RG $ResourceGroup · cannot set appSetting" }

    Write-Host "[Onboard-CategorySurgical] merging appSetting $appSettingName=$immId on FA $faName (az appsettings set · merges)"
    az functionapp config appsettings set `
        --resource-group $ResourceGroup `
        --name $faName `
        --settings "$appSettingName=$immId" `
        --output none
    if ($LASTEXITCODE -ne 0) { throw "[Onboard-CategorySurgical] appsettings set FAILED (az exit $LASTEXITCODE)" }

    # ─── Ensure the per-DCR Monitoring Metrics Publisher role POST-DEPLOY (idempotent · like the appSetting merge) ──
    # Defect-1 fix (WS-card-sync): the role is created with the EXACT SAME deterministic NAME deploy/mainTemplate.json
    # computes via ARM `guid(resourceId('…/dataCollectionRules', dcrName), principalId, 'MMP-DCR-<cat>')`, reproduced
    # offline by Get-XdrArmGuid (Parser · the single-source ARM-guid() reproduction · RFC-4122 v5 / fixed Azure
    # namespace). WHY the explicit name matters: ARM keys roleAssignment idempotency on the assignment NAME. If this
    # surgical onboard let `az role assignment create` mint a RANDOM-GUID name, a later FULL mainTemplate re-deploy
    # (the GA fresh-deploy gate · the failed full-sync) would PUT the role under the guid()-name and 409
    # RoleAssignmentExists against the existing random-named tuple assignment → whole-deployment rollback. Creating it
    # here under the template's guid()-name makes the re-deploy an idempotent SAME-NAME no-op. az role assignment create
    # is still tuple-idempotent (we check the tuple first), so it works for a fresh category AND a re-onboard. WITHOUT
    # this role the FA SAMI cannot publish to the DCR → silent 403 / 0 rows (the P9.5-iii class). SP needs roleAssignments/write.
    $dcrName = az deployment group show --resource-group $ResourceGroup --name $deploymentName --query 'properties.outputs.dcrName.value' -o tsv 2>$null
    $subId   = az account show --query id -o tsv 2>$null
    $faPid   = az functionapp identity show --resource-group $ResourceGroup --name $faName --query principalId -o tsv 2>$null
    if ($dcrName -and $subId -and $faPid) {
        $dcrId = "/subscriptions/$subId/resourceGroups/$ResourceGroup/providers/Microsoft.Insights/dataCollectionRules/$dcrName"
        # Deterministic role-assignment name == the mainTemplate's `guid(resourceId(DCR), principalId, 'MMP-DCR-<cat>')`.
        # The first guid() arg is the DCR's ARM resourceId STRING — which inside the role's same-RG (connector RG) nested
        # deployment is exactly $dcrId computed above (/subscriptions/.../dataCollectionRules/<dcrName>).
        $roleAssignmentName = Get-XdrArmGuid -Arguments @($dcrId, $faPid, "MMP-DCR-$catLower")
        Write-Host "[Onboard-CategorySurgical] deterministic per-DCR role name (== mainTemplate guid()) : $roleAssignmentName"
        $haveRole = $false
        try {
            $ra = az role assignment list --assignee $faPid --scope $dcrId --role 'Monitoring Metrics Publisher' -o json 2>$null | ConvertFrom-Json
            $haveRole = @($ra).Count -gt 0
        } catch { $haveRole = $false }
        if ($haveRole) {
            # Tuple already granted. Surface whether it is under the DETERMINISTIC name (a full re-deploy will be a
            # clean idempotent no-op) or a legacy RANDOM name (a full mainTemplate re-deploy would 409 RoleAssignmentExists
            # against it · Defect-1 drift). We do NOT delete/recreate here (avoid a momentary publish-permission gap on a
            # live DCR); the name only governs the FULL-deploy path, and this onboard's own ingest works under either name.
            $existingNames = @(@($ra) | ForEach-Object { [string]$_.name })
            if ($existingNames -contains $roleAssignmentName) {
                Write-Host "[Onboard-CategorySurgical] per-DCR Monitoring Metrics Publisher role already present on $dcrName under the deterministic name · skip (full re-deploy is a clean no-op)"
            } else {
                Write-Warning "[Onboard-CategorySurgical] per-DCR MMP role present on $dcrName but under name(s) [$($existingNames -join ', ')], NOT the deterministic '$roleAssignmentName'. The FA SAMI can publish (ingest is fine), but a FULL mainTemplate re-deploy would 409 RoleAssignmentExists (Defect-1). To converge: delete the legacy assignment then re-run -Apply (or let the targeted role path recreate it deterministically)."
            }
        } else {
            Write-Host "[Onboard-CategorySurgical] granting FA SAMI Monitoring Metrics Publisher on $dcrName (deterministic name $roleAssignmentName) ..."
            # --name pins the assignment to the template's guid() so a later full mainTemplate deploy is a same-name no-op.
            $grantOut = az role assignment create --assignee-object-id $faPid --assignee-principal-type ServicePrincipal --role 'Monitoring Metrics Publisher' --scope $dcrId --name $roleAssignmentName --output none 2>&1 | Out-String
            if ($LASTEXITCODE -ne 0 -and ($grantOut -notmatch 'RoleAssignmentExists')) { throw "[Onboard-CategorySurgical] per-DCR role grant FAILED (az exit $LASTEXITCODE): $grantOut" }
        }
    } else {
        Write-Warning "[Onboard-CategorySurgical] could not resolve dcrName/sub/FA-principalId · per-DCR role NOT ensured. Verify manually: the FA SAMI needs Monitoring Metrics Publisher on the DCR or ingest will 403 (silent 0 rows)."
    }

    # ─── Sync the Sentinel connector card to the current shipped-category set (Defect-3 fix · WS-card-sync) ──
    # Onboard-CategorySurgical historically deployed the table + DCR + appSetting + per-DCR role but NEVER the connector
    # card (dataConnectorDefinition) → the card drifted BEHIND the onboarded categories (the live card froze at the
    # initial 6-category deploy while the repo advanced). The card is the SINGLE Sentinel V3 dataConnectorDefinition for
    # the whole connector (one card, N category tables); deploy/connector-card-only.json (single-sourced from the
    # mainTemplate card by Build-MainTemplate · enumerates ALL committed shipped categories) is deployed here to the
    # WORKSPACE resource group to bring the live card in sync with the just-onboarded category. It touches ONLY the
    # dataConnectorDefinition (0 foundation resources · NO FA zip reset · NO roles), so it is safe to deploy post-add.
    # NON-FATAL: the category's data path (table/DCR/appSetting/role) already landed above; a card-sync failure WARNS
    # (the card can be re-synced standalone) and does NOT fail the onboard. Skip with -SkipConnectorCardSync.
    if (-not $SkipConnectorCardSync) {
        if (-not (Test-Path $ConnectorCardTemplate)) {
            Write-Warning "[Onboard-CategorySurgical] connector-card template not found: $ConnectorCardTemplate · card NOT synced. Run dev-tools/Build-MainTemplate.ps1 to (re)generate it, then deploy it standalone, OR re-run with -SkipConnectorCardSync to suppress this."
        } else {
            $cardDeployName = "xdrlr-cardsync-$catLower-$epoch"
            Write-Host ""
            Write-Host "[Onboard-CategorySurgical] syncing the Sentinel connector card (all shipped categories) to workspace RG '$wsRG' (card-only · no foundation touched) ..."
            az deployment group create `
                --resource-group $wsRG `
                --template-file $ConnectorCardTemplate `
                --parameters "workspaceResourceId=$pWorkspaceResId" "connectorDefinitionName=$ConnectorDefinitionName" `
                --name $cardDeployName `
                --mode Incremental `
                --output none 2>&1 | Out-Null
            if ($LASTEXITCODE -ne 0) {
                Write-Warning "[Onboard-CategorySurgical] connector-card sync deployment FAILED (az exit $LASTEXITCODE · NON-FATAL · the category data already landed). Re-sync standalone: az deployment group create --resource-group $wsRG --template-file `"$ConnectorCardTemplate`" --parameters workspaceResourceId=$pWorkspaceResId connectorDefinitionName=$ConnectorDefinitionName"
            } else {
                Write-Host "[Onboard-CategorySurgical] connector card synced · the gallery now lists every shipped category (incl. $Portal/$Category)." -ForegroundColor Green
            }
        }
    } else {
        Write-Host "[Onboard-CategorySurgical] -SkipConnectorCardSync · connector card NOT synced (the card may now lag the onboarded categories · sync it via deploy/connector-card-only.json)."
    }

    # ─── Post-recreate checkpoint reset (BoundaryDeduped-after-recreate fix · live-caught 2026-06-25) ──
    # A drop+recreate of the table makes it EMPTY, but the FA's exactly-once checkpoint BOUNDARY is unchanged — so on the
    # next poll the runtime sees the rows as already-sent → Entry.Poll.BoundaryDeduped → ZERO rows land in the now-empty
    # recreated table (live-proven: after recreating Defender_ExposureManagement_CL + Defender_EndpointManagement_CL the
    # GetTvmRiskScore/List polls SUCCEEDED but BoundaryDeduped → 0 rows, until a manual Save-XdrCheckpointReset). Fix at
    # source: if we recreated the table this run, AUTO-reset the checkpoint here so the FA re-emits from a clean baseline
    # into the empty table. NON-FATAL — the table/DCR/appSetting already landed; a reset failure WARNS with the manual
    # command and does NOT fail the onboard. -StorageAccount defaults from $env:XDRLR_STORAGE_ACCOUNT; when empty the
    # child tool self-resolves the FA storage account from .env.local (XDRLR_STORAGE_ACCOUNT).
    if ($didRecreateTable) {
        $resetTool = Join-Path $PSScriptRoot 'Save-XdrCheckpointReset.ps1'
        $resetArgs = @('-NoProfile', '-NonInteractive', '-File', $resetTool,
            '-Portal', $Portal, '-Category', $Category, '-ResourceGroup', $ResourceGroup,
            '-Reason', 'schema-change', '-Apply')
        if ($StorageAccount) { $resetArgs += @('-StorageAccount', $StorageAccount) }
        Write-Host ""
        Write-Host "[Onboard-CategorySurgical] table was recreated → Save-XdrCheckpointReset (Reason=schema-change) so the FA re-emits from a clean baseline into the empty table (BoundaryDeduped-after-recreate fix)." -ForegroundColor Yellow
        try {
            & pwsh @resetArgs
            if ($LASTEXITCODE -ne 0) {
                Write-Warning "[Onboard-CategorySurgical] post-recreate Save-XdrCheckpointReset FAILED (NON-FATAL · az exit $LASTEXITCODE) — run it manually: pwsh tools/Save-XdrCheckpointReset.ps1 -Portal $Portal -Category $Category -Reason schema-change -Apply, else the recreated table '$tableName' stays empty (BoundaryDeduped)."
            } else {
                Write-Host "[Onboard-CategorySurgical] checkpoint reset done · the next TimerTrigger re-emits $Portal/$Category from a clean baseline into the empty '$tableName'." -ForegroundColor Green
            }
        } catch {
            Write-Warning "[Onboard-CategorySurgical] post-recreate Save-XdrCheckpointReset FAILED (NON-FATAL) — run it manually: pwsh tools/Save-XdrCheckpointReset.ps1 -Portal $Portal -Category $Category -Reason schema-change -Apply, else the recreated table '$tableName' stays empty (BoundaryDeduped). Error: $($_.Exception.Message)"
        }

        # ─── DCR schema-propagation lag notice (PROPAGATION-PENDING · live-caught this session) ──────────────
        # When the recreate ADDED ≥1 NEW column, Azure's propagation of the recreated table's schema to the DCR/DCE
        # INGESTION endpoint lags ~10-15 min. So the FIRST re-emit after the checkpoint reset above can land the NEW
        # column(s) EMPTY while every PRE-EXISTING column + id flow normally (live-proven: a MachineSecurityStates re-poll
        # ~1h later landed machineName + the 18-rule asrConfigurationStatesJson correctly). This TRANSIENTLY false-negatives
        # the §4.B typed-populated gate (D8f) for ONLY the new cols until propagation completes and the op is re-polled.
        # Emit a prominent, structured notice keyed off the ACTUAL added-column list (generic · any category/columns) so the
        # re-prove allows a settle + re-polls before concluding the new cols are broken. Marker token: PROPAGATION-PENDING.
        if ($addedColumns.Count -gt 0) {
            $addedList = ($addedColumns -join ', ')
            Write-Host ""
            Write-Host "  ┌─────────────────────────────────────────────────────────────────────────────────────────┐" -ForegroundColor Cyan
            Write-Host "  │ PROPAGATION-PENDING · DCR schema propagation for the NEW column(s) takes ~10-15 min        │" -ForegroundColor Cyan
            Write-Host "  └─────────────────────────────────────────────────────────────────────────────────────────┘" -ForegroundColor Cyan
            Write-Host "[Onboard-CategorySurgical] PROPAGATION-PENDING · this recreate ADDED $($addedColumns.Count) NEW column(s) to '$tableName': $addedList" -ForegroundColor Cyan
            Write-Host "[Onboard-CategorySurgical] PROPAGATION-PENDING · Azure DCR schema propagation to the ingestion endpoint takes ~10-15 min, so the FIRST re-emit of these op(s) after the checkpoint reset may land the NEW column(s) [$addedList] EMPTY — while every PRE-EXISTING column + id flow normally." -ForegroundColor Cyan
            Write-Host "[Onboard-CategorySurgical] PROPAGATION-PENDING · the D8f §4.B typed-populated gate will CORRECTLY but TRANSIENTLY flag these new column(s) empty until propagation completes. Do NOT conclude the new column(s) are broken yet." -ForegroundColor Cyan
            Write-Host "[Onboard-CategorySurgical] PROPAGATION-PENDING · the §4.B re-prove MUST allow a ~15-min settle, then RE-POLL the affected op(s) — e.g. pwsh tools/Save-XdrCheckpointReset.ps1 -Portal $Portal -Category $Category -OperationKey <op> -Apply — and re-run Verify-DeployedConnector.ps1 BEFORE concluding the new column(s) [$addedList] are broken." -ForegroundColor Cyan
            Write-Host ""
        }
    }

    Write-Host ""
    Write-Host "================================================================"
    Write-Host "Onboard-CategorySurgical · APPLIED · $Portal/$Category"
    Write-Host "  DCR immutableId : $immId"
    Write-Host "  appSetting      : $appSettingName (merged · FA NOT bounced by ARM)"
    Write-Host "  connector card  : $(if ($SkipConnectorCardSync) { 'NOT synced (-SkipConnectorCardSync)' } else { 'synced to all shipped categories' })"
    if ($didRecreateTable) { Write-Host "  checkpoint      : reset (Reason=schema-change · table recreated → FA re-emits from a clean baseline · BoundaryDeduped-after-recreate fix)" }
    if ($didRecreateTable -and $addedColumns.Count -gt 0) { Write-Host "  new columns     : $($addedColumns -join ', ') · PROPAGATION-PENDING — ~10-15 min DCR schema lag · §4.B re-prove MUST settle ~15 min + re-poll the op(s) before judging these new cols (see the PROPAGATION-PENDING block above)" -ForegroundColor Cyan }
    Write-Host "  Next: pwsh tools/Verify-DeployedConnector.ps1 -Category $Category"
    Write-Host "================================================================"
    exit 0
}
finally {
    Remove-Item $tmpTemplate -Force -ErrorAction SilentlyContinue
}
